### ISSUE TITLE
Add frontend changes to manage the form & the submissions.

### ISSUE THREAD

**Issue by sumanranjanpanda** [bigbinary/neeto-form-engine#7]
<img width="1256" alt="Screenshot 2022-04-19 at 10 52 03 PM" src="https://user-images.githubusercontent.com/1097929/164203923-9b621b28-64f0-4f82-9a56-a86621a1a885.png">

**Comment by ajmaln** [comment]
Form Engine UI Demo:

https://vimeo.com/702013878/954fab9253

cc: @sumanranjanpanda
